baseURL: ""
languageCode: en-gb
title: James Royall Portfolio
theme: PaperMod

canonifyURLs: true

menu:
  main:
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 10

params:
  homeInfoParams:
    Title: "Data analysis"
    Content: >
      Some examples of my work below using pandas, matplotlib, seaborn, geopandas, etc.
      Tableau visualisations are at the last of the four links.

  socialIcons: 
    - name: linkedin
      url: "https://www.linkedin.com/in/jamesroyall/"
    - name: twitter
      url: "https://twitter.com/jamesroyall"
    - name: github
      url: "https://github.com/stepons/postworkings"
    - name: tableau
      url: "https://public.tableau.com/app/profile/james.royall/vizzes"